FROM ubuntu:16.04

ENV DEBIAN_FRONTEND=noninteractive

# Install pdf2htmlEX and its dependencies
RUN apt-get update && apt-get install -y \
    pdf2htmlex \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /pdf

# Set default entrypoint to pdf2htmlEX
ENTRYPOINT ["pdf2htmlEX"]